### 자바 예외 종류
```
Throwable
ㄴ Error   # 컴파일러가 예외 처리 코드 여부를 검사하지 않음
ㄴ Exception
    - ClassNotFound
    - Interupted
    - ...
    ㄴ RuntimeException  # 예외 처리 코드가 없어도 컴파일 되지만, 실행중에 발생하면 프로그램이 종료됨
        - NullPointer
        - ArrayOutIndex
        - ...
```
### 다중 catch 사용시 주의점
- 다중 catch를 사용하면 예외의 종류에 따라 다른 처리를 할 수 있다.
- 다만 catch문을 여러개 사용한다고 해서 해당 catch문이 해당 예외가 일어나기만 한다면 다 해당될 것이라고 생각할 순 없다.
- catch 블록이 여러 개라 할지라도 catch 블록은 단 하나만 실행된다. try에서 제일 처음 발생한 에러에 대한 예외만 처리하기 때문이다. 
  ```java
     String [] strArr = {"100","1oo"};
          try {
              int tmp1 = Integer.parseInt(strArr[3]); // ArrayIndexOutOfBoundsException 발생
              int tmp2 = Integer.parseInt(strArr[1]); // NumberFormatException 발생
          } catch(NumberFormatException e) {
              System.out.println("NumberFormatException");
          } catch (ArrayIndexOutOfBoundsException e) {
              System.out.println("ArrayIndexOutOfBoundsException");
          } catch (Exception e) {
            System.out.println("Exception");
        }
  ```
  ```
  ArrayIndexOutOfBoundsException
  ```
- 위와 같은 문제를 해결하기 위해 코드 하나 실행시 마다 try-catch하게 구조를 바꾸면 의도대로 예외가 처리된다. 
  ```java
       String[] strArr = {"100", "1oo"};
        for (int i = 0; i <= strArr.length; i++) {
            try {
                int val = Integer.parseInt(strArr[i]);
                System.out.println(val);
            } catch (ArrayIndexOutOfBoundsException e) {
                System.out.println("ArrayIndexOutOfBoundsException");
            } catch (NumberFormatException e) {
                System.out.println("NumberFormatException");
            } catch (Exception e) {
                System.out.println("Exception");
            }
        }
  ```
  ```
  100
  NumberFormatException
  ArrayIndexOutOfBoundsException
  ```
- 처리해야 할 예외 클래스들이 상속 관계에 있을 때는, 하위 클래스 catch 블록을 먼저 작성해야 한다. : 구체적인거 먼저!
  - 예외가 발생하면 catch 블록은 위에서부터 차례대로 검사 대상이 되는데, 하위 예외도 상위 클래스 타입이므로 상위 클래스 catch 블록이 먼저 검사 대상이 되면 안된다. 
- 두 개 이상의 예외를 하나의 catch 블록으로 동일하게 예외 처리 하고 싶을 떈 예외 클래스를 기호 `|`로 연결한다. 
  - JDK 1.7 부터 가능하다.

### 예외 관련 메서드
- 에러 출력
```
1. e.getMessage() : 예외가 발생한 이유
2. e.toString() : 1 + 예외 종류 
3. e.printStackTrace : 2 + 예외가 어디서 발생했는지 추적내용 
```